name: CI

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
 
    # Setup Node.js
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 10.7.0

    - name: Install modules
      run: node app.js

    - name: Generate image
      run: node app.js

    - name: Git Commit and Push
      uses: github-actions-x/commit@v2.6
      with:
        # Github Token with commit access
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Specify commit message
        commit-message: Updated rendered image automatically
        # Specific files to add.
        files: result.png